exp:
  name: '&eСтатистика'
  lore:
    - '&6Уровень максимального здоровья: &c%health%'
    - '&6Уровень силы: &c%damage%'
    - '&6Уровень скорости: &c%speed%'
    - '&6Уровень крита: &c%krit%'
    - '&6Уровень шанса критического урона: &c%kritchance%'
    - '&6Уровень сопротивления урону: &c%takeover%'
health:
  name: '&eМаксимальное здоровье'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык увеличивает ваше &cмаксимальное здоровье'
    - '&6Каждый уровень повышает &cздоровье &6на &c0.5❤'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
damage:
  name: '&eСила'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык увеличивает вашу &cсилу'
    - '&6Каждый уровень повышает &cурон &6на &c0.25⚔'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
speed:
  name: '&eСкорость'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык увеличивает вашу &cскорость'
    - '&6Каждый уровень повышает &cскорость &6на &c3%'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
krit:
  name: '&eКритический урон'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык увеличивает ваш &cкритический урон'
    - '&6Каждый уровень повышает &cкритический урон &6на &c10%'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
kritchance:
  name: '&eШанс критического удара'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык увеличивает ваш &cшанс на критический удар'
    - '&6Каждый уровень повышает &cшанс &6на &c3%'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
takeover:
  name: '&eСопротивление урону'
  lore:
    - '&6Ваш уровень навыка: &c%lvl%'
    - '&6Данный навык позволяет увернуться от удара'
    - '&6Каждый уровень повышает &cшанс уворота &6на &c3%'
    - '&6Чтобы прокачать навык нажми &cSHIFT &6+ &cЛКМ'
    - '&6Стоимость прокачки: &c%price_lvl% &6уровней'
option_on:
  name: '&aСообщения включены'
  lore:
    - '&6SHIFT + ЛКМ чтобы выключить сообщения'
option_off:
  name: '&cСообщения выключены'
  lore:
    - '&6SHIFT + ЛКМ чтобы включить сообщения'
messages:
  upgrade: '&6┃ &cВы улучшили навык &c%skill%&6, теперь ваш уровень &c%lvl%'
  maxlvl: '&6┃ &cВы уже максимально улучшили навык!'
  noexp: '&6┃ &cУ Вас недостаточно уровней опыта'
  nomoney: 'У Вас недостаточно гейских денег'
  damage: '&6┃ &cВы нанесли урон игроку &6%player%&c, равный &6%damage%⚔'
  tdamage: '&6┃ &cВы получили урон &6%damage% &cот игрока &6%player%'
  krit: '&6┃ &cВы нанесли критический удар игроку &6%player%&c, урон составил: &6%damage%⚔'
  tkrit: '&6┃ &cИгрок &6%player% &cнанес вам критический удар, урон составил: &6%damage%⚔'
  takeover: '&6┃ &cИгрок &6%player% &cувернулся от вашего удара'
  ttakeover: '&6┃ &cВы увернулись от удара игрока &6%player%'
  replace:
    health: 'максимальное здоровье'
    damage: 'сила'
    speed: 'скорость'
    krit: 'критический урон'
    kritchance: 'шанс критического удара'
    takeover: 'сопротивление урону'
inventory: '&6&lНавыки'
start_price_exp: 5